---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.10.4

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: setup
    run_list:
      - recipe[apt]
      - recipe[cli-application::setup]
    attributes:
      carnegielearning:
        local_nets:
          - 10.0.0.0/24
          - 192.168.1.1/24
